[project]
id      = "sieve"
version = "0.4.1"
src     = "src"
out     = "out/{target.name}/{profile.name}"

[target.linux-x86_64]
default = true
isa     = "x86_64"
os      = "linux"
abi     = "sysv64"

[profile.debug]
default       = true
opt           = 0
debug         = true
simd          = "scalarize"
vectorize     = false
float_reassoc = false

[profile.release]
opt           = 2
debug         = false
simd          = "scalarize"
vectorize     = true
float_reassoc = false

[artifact.sieve]
kind    = "bin"
entry   = "main.mach"
out     = "bin/sieve{artifact.suffix}"
targets = ["*"]
link    = []
need    = []

[dep.std]
git = "https://github.com/briar-systems/mach-std"
ref = "tag/v2.0.0"
